### ISSUE TITLE
How do I run np locally?

### ISSUE THREAD

**Issue by bquorning** [marcandre/np#4]
Hey @marcandre. While trying to run `np` locally, I found that:

1. It requires Ruby 3.1 (3.2 won’t work), but doesn’t have a .ruby-version file.
2. It has a gemspec, but is a service. Or can it be used as a gem too?
3. Running `rake serve` isn’t documented in Readme. Also, I think I need to compile assets first.
4. There is a `build_assets` rake task which seems to require [Parcel](https://parceljs.org/) (could it be added to package.json?). But even after installing it, I cannot figure out how to build the assets.

**Comment by marcandre** [comment]
Sorry you're running into difficulties

1. `.ruby-version` is git-ignored, but `np` should work with all (recent) Ruby versions. I'm installing 3.2 to check it out (my main MacBook is dead)
2. Good point. It's not meant to be used as a library, but then... I guess it could?
3. Added, thanks. I think only `npm install` is needed, I added it to `bin/setup`, and updated the README
4. Oohhh, I haven't had to change assets in years, so I forget exactly what's up with this. ~It's not required for local use.~

**Comment by marcandre** [comment]
Mmm, looks like `parcel` is required even locally, you are right. I'll add it to the package.json

**Comment by marcandre** [comment]
Added `parcel` and tweaked its invocation using `npx`.

Also: fixed the [broken dependency for Ruby 3.2](https://github.com/marcandre/require_relative_dir/pull/4)

`bin/setup` should fix issues for you. Please let me know if you run into issues.

**Comment by bquorning** [comment]
Parcel still fails for me with `error: unknown option '--global'`.
